# 02. 텐서의 연산

In [ ]:
import torch
import torchvision
import numpy as np

# print(torch.__version__)
# print(torchvision.__version__)

## 2-1. 산술 연산

In [ ]:
x = torch.ones(2,2)
print(x)
# tensor([[1., 1.],
#         [1., 1.]])

x *= 2
print(x)
# tensor([[2., 2.],
#         [2., 2.]])

x += 3
print(x)
# tensor([[5., 5.],
#         [5., 5.]])

In [ ]:
# 연산의 결과가 원본을 변경하지는 않음

x = torch.tensor([[1,2], [3,4]])
y = torch.tensor([[4,3], [2,1]])

# 더하기
add = torch.add(x, y)
print(add)
print(x + y)
# tensor([[5, 5],
#         [5, 5]])

# 빼기
sub = torch.sub(x, y)
print(sub)
print(x - y)
# tensor([[-3, -1],
#         [ 1,  3]])

# 곱하기
mul = torch.mul(x, y)
print(mul)
print(x * y)
# tensor([[4, 6],
#         [6, 4]])

# 나누기
div = torch.div(x, y)
print(div)
print(x / y)
# tensor([[0.2500, 0.6667],
#         [1.5000, 4.0000]])

## 2-2. 바꿔치기 연산(in-place)
- 연산자의 뒤에 _ 를 추가한 형태로 사용

In [ ]:
x = torch.tensor([[5,6], [7,8]])
y = torch.tensor([[3,1], [4,2]])

x.add_(y)
print(x)
# tensor([[ 8,  7],
#         [11, 10]])

# fill
x.fill_(0)
print(x)
# tensor([[0, 0],
#         [0, 0]])

## 2-3. 각종 연산

In [ ]:
x = torch.tensor([[1.1,2.2,3.3], [4,5,6], [-1,-3.14,-6]])

# 수학 연산
print("절대값", torch.abs(x))
# 절대값 tensor([[1.1000, 2.2000, 3.3000],
#         [4.0000, 5.0000, 6.0000],
#         [1.0000, 3.1400, 6.0000]])

print("올림", torch.ceil(x))
# 올림 tensor([[ 2.,  3.,  4.],
#         [ 4.,  5.,  6.],
#         [-1., -3., -6.]])

print("반올림", torch.round(x))
# 반올림 tensor([[ 1.,  2.,  3.],
#         [ 4.,  5.,  6.],
#         [-1., -3., -6.]])

print("내림", torch.floor(x))
# 내림 tensor([[ 1.,  2.,  3.],
#         [ 4.,  5.,  6.],
#         [-1., -4., -6.]])

print("모든 원소의 합", torch.sum(x))
# 모든 원소의 합 tensor(11.4600)

print("모든 원소의 곱", torch.prod(x))
# 모든 원소의 곱 tensor(-18054.7500)

In [ ]:
# 통계관련 연산
print("최소값", torch.min(x))
# 최소값 tensor(-6.)

print("최대값", torch.max(x))
# 최대값 tensor(6.)

print("최소값의 인덱스", torch.argmin(x))
# 최소값의 인덱스 tensor(8)

print("최대값의 인덱스", torch.argmax(x))
# 최대값의 인덱스 tensor(5)

# 최소값과 최대값을 정하고 그 범위 안으로 값을 맞춤
print("클램프", torch.clamp(x, -2, 2))
# 클램프 tensor([[ 1.1000,  2.0000,  2.0000],
#         [ 2.0000,  2.0000,  2.0000],
#         [-1.0000, -2.0000, -2.0000]])

print("평균값", torch.mean(x))
# 평균값 tensor(1.2733)

print("표준편차", torch.std(x))
# 표준편차 tensor(3.9719)

print("중복제거", torch.unique(torch.tensor([1,1,1,2,2,2,3,3,3,4,4])))
# 중복제거 tensor([1, 2, 3, 4])

In [ ]:
# 차원 지정
x = torch.tensor([[1.1,2.2,3.3], [4,5,6], [-1,-3.14,-6]])

print("열의 합", torch.sum(x, dim=0))
print("행의 합", torch.sum(x, dim=1))
# 열의 합 tensor([4.1000, 4.0600, 3.3000])
# 행의 합 tensor([  6.6000,  15.0000, -10.1400])

print("열의 최대값", torch.max(x, dim=0))
# 열의 최대값 torch.return_types.max(
# values=tensor([4., 5., 6.]),
# indices=tensor([1, 1, 1]))

## 2-4. 내적(dot product) / 행렬의 곱셈

In [ ]:
x = torch.tensor([[1,2], [3,4]])
y = torch.tensor([[5,6], [7,8]])

print(torch.matmul(x,y))
# tensor([[19, 22],
#         [43, 50]])