# 03. 텐서의 조작

In [ ]:
import torch
import torchvision
import numpy as np

# print(torch.__version__)
# print(torchvision.__version__)

## 3-1. 인덱싱, 슬라이싱
- NumPy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

print(x[1,1])
# tensor(5)
print(x[2,0])
# tensor(7)
print(x[0, :])
# tensor([1, 2, 3])
print(x[:, 2])
# tensor([3, 6, 9])

In [ ]:
# fancy 인덱싱
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

print(x[[0,1,2], [0,1,2]])
# tensor([1, 5, 9])

# boolean 인덱싱
print(x[x > 5])
# tensor([6, 7, 8, 9])

In [ ]:
# 값 변경
x = torch.tensor([10,20,30,40,50])

# 인덱스를 사용해서 값 변경
x[0] = 100
print(x)
# tensor([100,  20,  30,  40,  50])

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200,300,400])
print(x)
# tensor([100, 200, 300, 400,  50])

## 3-2. 텐서의 크기, 모양 변경
- ```torch.view()```

In [ ]:
x = torch.randn(4,5)
print(x)
# tensor([[ 1.6556,  1.1775,  0.7074,  0.6514,  1.2222],
#         [-3.4192,  0.5839, -0.5892,  0.9749, -0.3656],
#         [-0.9102, -1.4960,  0.4842,  0.2422, -0.6213],
#         [-1.2977,  0.1044, -1.1074, -0.6357,  0.8306]])

y = x.view(20)
print(y)
# tensor([ 1.6556,  1.1775,  0.7074,  0.6514,  1.2222, -3.4192,  0.5839, -0.5892,
#          0.9749, -0.3656, -0.9102, -1.4960,  0.4842,  0.2422, -0.6213, -1.2977,
#          0.1044, -1.1074, -0.6357,  0.8306])

z = y.view(5, -1) # -1 -> 자동 계산
print(z)
# tensor([[-1.3062,  0.7716, -0.2739,  0.2950],
#         [ 0.0949, -0.3929, -0.3141, -2.0559],
#         [-1.0060,  1.5867,  1.1121, -0.1188],
#         [-1.6458, -1.6057,  0.3260,  0.7940],
#         [-0.4304,  0.6981,  0.0717,  1.4957]])

## 3-3. 텐서의 숫자값 얻기
- ```tensor.item()``` : 스칼라 값 하나만 존재해야 사용 가능

In [ ]:
x = torch.rand(1)
print(x)
print(x[0])
print(x.item())
# tensor([0.3532])
# tensor(0.3532)
# 0.3532150983810425

## 3-4. 차원 축소 및 증가

### 차원 축소(제거)
- ```torch.squeeze()``` : 크기가 1인 차원을 제거함

In [ ]:
t = torch.rand(3,1,3)
print(t)
print(t.shape)
# tensor([[[0.6100, 0.5116, 0.2696]],
#         [[0.8604, 0.1251, 0.0841]],
#         [[0.4251, 0.3889, 0.3191]]])
# torch.Size([3, 1, 3])

ts = torch.squeeze(t)
print(ts)
print(ts.shape)
# tensor([[0.6100, 0.5116, 0.2696],
#         [0.8604, 0.1251, 0.0841],
#         [0.4251, 0.3889, 0.3191]])
# torch.Size([3, 3])

### 차원 증가(생성)
- ```torch.unsqueeze()``` : dim 설정에 따라 차원을 증가시킴
    - dim : 하나의 차원이 추가되는 인덱스

In [ ]:
t = torch.rand(3,3,3)
print(t.shape)
# torch.Size([3, 3, 3])

ts1 = torch.unsqueeze(t, dim=0)
print(ts1.shape)
# torch.Size([1, 3, 3, 3])

ts2 = torch.unsqueeze(t, dim=1)
print(ts2.shape)
# torch.Size([3, 1, 3, 3])

ts3 = torch.unsqueeze(t, dim=2)
print(ts3.shape)
# torch.Size([3, 3, 1, 3])

ts4 = torch.unsqueeze(t, dim=3)
print(ts4.shape)
# torch.Size([3, 3, 3, 1])

## 3-5. 텐서간 결합

- ```torch.stack()``` : 동일한 형식의 텐서를 새롭게 그룹화 함 -> 새로운 차원이 생성됨

In [ ]:
x = torch.tensor([1,4])
y = torch.tensor([2,5])
z = torch.tensor([3,6])

result = torch.stack([x,y,z])

print(result)
# tensor([[1, 4],
#         [2, 5],
#         [3, 6]])

In [ ]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[5,6], [7,8]])

result2 = torch.stack([a, b])

print(result2)
# tensor([[[1, 2],
#          [3, 4]],
#         [[5, 6],
#          [7, 8]]])

- ```torch.cat()``` : 데이터를 하나의 텐서로 병합 -> 새로운 차원 생성X

In [ ]:
a = torch.tensor([[1,2], [3,4], [5,6]])
b = torch.tensor([[7,8], [9,10]])

result = torch.cat((a, b))

print(result)
# tensor([[ 1,  2],
#         [ 3,  4],
#         [ 5,  6],
#         [ 7,  8],
#         [ 9, 10]])

In [ ]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[7,8], [9,10]])

result2 = torch.cat((a, b), dim=1)

print(result2)
# tensor([[ 1,  2,  7,  8],
#         [ 3,  4,  9, 10]])

## 3-6. 텐서 나누기

- ```torch.chunk()``` : 텐서를 지정한 개수에 따라 나눔
    - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐

In [ ]:
a = torch.rand(3,7)
print(a)
# tensor([[0.1705, 0.9585, 0.9547, 0.8704, 0.1652, 0.5958, 0.9330],
#         [0.7946, 0.5683, 0.9037, 0.7619, 0.3425, 0.0082, 0.4182],
#         [0.6893, 0.9638, 0.4572, 0.4528, 0.0766, 0.4159, 0.0359]])

a1, a2, a3 = torch.chunk(a, 3)

print(a1)
# tensor([[0.1705, 0.9585, 0.9547, 0.8704, 0.1652, 0.5958, 0.9330]])

print(a2)
# tensor([[0.7946, 0.5683, 0.9037, 0.7619, 0.3425, 0.0082, 0.4182]])

print(a3)
# tensor([[0.6893, 0.9638, 0.4572, 0.4528, 0.0766, 0.4159, 0.0359]])

In [ ]:
a = torch.rand(3,7)
print(a)
# tensor([[0.8378, 0.5858, 0.4332, 0.4985, 0.0919, 0.8994, 0.7126],
#         [0.9848, 0.8618, 0.6856, 0.3227, 0.2699, 0.8010, 0.6921],
#         [0.0596, 0.2603, 0.2632, 0.7922, 0.5997, 0.2149, 0.7465]])

a1, a2, a3 = torch.chunk(a, 3, dim=1)

print(a1)
# tensor([[0.8378, 0.5858, 0.4332],
#         [0.9848, 0.8618, 0.6856],
#         [0.0596, 0.2603, 0.2632]])

print(a2)
# tensor([[0.4985, 0.0919, 0.8994],
#         [0.3227, 0.2699, 0.8010],
#         [0.7922, 0.5997, 0.2149]])

print(a3)
# tensor([[0.7126],
#         [0.6921],
#         [0.7465]])

- ```torch.split()``` : 지정한 사이즈에 따라 나눔
    - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐

In [ ]:
a = torch.rand(3,7)
print(a)
# tensor([[0.7691, 0.8303, 0.2884, 0.1934, 0.3759, 0.3085, 0.9404],
#         [0.0326, 0.4732, 0.2993, 0.2168, 0.2406, 0.6826, 0.1089],
#         [0.1272, 0.9000, 0.9769, 0.7887, 0.7715, 0.1723, 0.1917]])

a1, a2, a3= torch.split(a, 3, dim=1)

print(a1)
# tensor([[0.7691, 0.8303, 0.2884],
#         [0.0326, 0.4732, 0.2993],
#         [0.1272, 0.9000, 0.9769]])

print(a2)
# tensor([[0.1934, 0.3759, 0.3085],
#         [0.2168, 0.2406, 0.6826],
#         [0.7887, 0.7715, 0.1723]])

print(a3)
# tensor([[0.9404],
#         [0.1089],
#         [0.1917]])

In [ ]:
# 쪼갤 열의 개수 지정 가능

a = torch.rand(3,7)
print(a)
# tensor([[0.1268, 0.6118, 0.6873, 0.4629, 0.7768, 0.9058, 0.4305],
#         [0.9716, 0.5351, 0.6880, 0.8228, 0.5792, 0.6738, 0.9804],
#         [0.4442, 0.8235, 0.4395, 0.2360, 0.4738, 0.6875, 0.7432]])

a1, a2, a3= torch.split(a, [1,1,5], dim=1)

print(a1)
# tensor([[0.1268],
#         [0.9716],
#         [0.4442]])

print(a2)
# tensor([[0.6118],
#         [0.5351],
#         [0.8235]])

print(a3)
# tensor([[0.6873, 0.4629, 0.7768, 0.9058, 0.4305],
#         [0.6880, 0.8228, 0.5792, 0.6738, 0.9804],
#         [0.4395, 0.2360, 0.4738, 0.6875, 0.7432]])